// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > src/types/database.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      units: {
        Row: {
          id: string
          name: string
          unit_number: string
          unit_type: 'troop' | 'pack' | 'crew' | 'ship'
          council: string | null
          district: string | null
          chartered_org: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          unit_number: string
          unit_type: 'troop' | 'pack' | 'crew' | 'ship'
          council?: string | null
          district?: string | null
          chartered_org?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          unit_number?: string
          unit_type?: 'troop' | 'pack' | 'crew' | 'ship'
          council?: string | null
          district?: string | null
          chartered_org?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          phone: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          phone?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          phone?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      unit_memberships: {
        Row: {
          id: string
          unit_id: string
          profile_id: string
          role: 'admin' | 'treasurer' | 'leader' | 'parent' | 'scout'
          is_active: boolean
          joined_at: string
        }
        Insert: {
          id?: string
          unit_id: string
          profile_id: string
          role: 'admin' | 'treasurer' | 'leader' | 'parent' | 'scout'
          is_active?: boolean
          joined_at?: string
        }
        Update: {
          id?: string
          unit_id?: string
          profile_id?: string
          role?: 'admin' | 'treasurer' | 'leader' | 'parent' | 'scout'
          is_active?: boolean
          joined_at?: string
        }
      }
      scouts: {
        Row: {
          id: string
          unit_id: string
          first_name: string
          last_name: string
          date_of_birth: string | null
          bsa_member_id: string | null
          patrol: string | null
          rank: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          unit_id: string
          first_name: string
          last_name: string
          date_of_birth?: string | null
          bsa_member_id?: string | null
          patrol?: string | null
          rank?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          unit_id?: string
          first_name?: string
          last_name?: string
          date_of_birth?: string | null
          bsa_member_id?: string | null
          patrol?: string | null
          rank?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      scout_guardians: {
        Row: {
          id: string
          scout_id: string
          profile_id: string
          relationship: string
          is_primary: boolean
        }
        Insert: {
          id?: string
          scout_id: string
          profile_id: string
          relationship?: string
          is_primary?: boolean
        }
        Update: {
          id?: string
          scout_id?: string
          profile_id?: string
          relationship?: string
          is_primary?: boolean
        }
      }
      accounts: {
        Row: {
          id: string
          unit_id: string
          code: string
          name: string
          account_type: 'asset' | 'liability' | 'equity' | 'income' | 'expense'
          parent_id: string | null
          is_system: boolean
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          unit_id: string
          code: string
          name: string
          account_type: 'asset' | 'liability' | 'equity' | 'income' | 'expense'
          parent_id?: string | null
          is_system?: boolean
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          unit_id?: string
          code?: string
          name?: string
          account_type?: 'asset' | 'liability' | 'equity' | 'income' | 'expense'
          parent_id?: string | null
          is_system?: boolean
          is_active?: boolean
          created_at?: string
        }
      }
      scout_accounts: {
        Row: {
          id: string
          scout_id: string
          unit_id: string
          balance: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          scout_id: string
          unit_id: string
          balance?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          scout_id?: string
          unit_id?: string
          balance?: number
          created_at?: string
          updated_at?: string
        }
      }
      journal_entries: {
        Row: {
          id: string
          unit_id: string
          entry_date: string
          description: string
          reference: string | null
          entry_type: string | null
          is_posted: boolean
          is_void: boolean
          void_reason: string | null
          created_by: string | null
          created_at: string
          posted_at: string | null
        }
        Insert: {
          id?: string
          unit_id: string
          entry_date: string
          description: string
          reference?: string | null
          entry_type?: string | null
          is_posted?: boolean
          is_void?: boolean
          void_reason?: string | null
          created_by?: string | null
          created_at?: string
          posted_at?: string | null
        }
        Update: {
          id?: string
          unit_id?: string
          entry_date?: string
          description?: string
          reference?: string | null
          entry_type?: string | null
          is_posted?: boolean
          is_void?: boolean
          void_reason?: string | null
          created_by?: string | null
          created_at?: string
          posted_at?: string | null
        }
      }
      journal_lines: {
        Row: {
          id: string
          journal_entry_id: string
          account_id: string
          scout_account_id: string | null
          debit: number
          credit: number
          memo: string | null
        }
        Insert: {
          id?: string
          journal_entry_id: string
          account_id: string
          scout_account_id?: string | null
          debit?: number
          credit?: number
          memo?: string | null
        }
        Update: {
          id?: string
          journal_entry_id?: string
          account_id?: string
          scout_account_id?: string | null
          debit?: number
          credit?: number
          memo?: string | null
        }
      }
      events: {
        Row: {
          id: string
          unit_id: string
          title: string
          description: string | null
          event_type: string | null
          location: string | null
          start_date: string
          end_date: string | null
          cost_per_scout: number | null
          cost_per_adult: number | null
          max_participants: number | null
          rsvp_deadline: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          unit_id: string
          title: string
          description?: string | null
          event_type?: string | null
          location?: string | null
          start_date: string
          end_date?: string | null
          cost_per_scout?: number | null
          cost_per_adult?: number | null
          max_participants?: number | null
          rsvp_deadline?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          unit_id?: string
          title?: string
          description?: string | null
          event_type?: string | null
          location?: string | null
          start_date?: string
          end_date?: string | null
          cost_per_scout?: number | null
          cost_per_adult?: number | null
          max_participants?: number | null
          rsvp_deadline?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      billing_records: {
        Row: {
          id: string
          event_id: string | null
          unit_id: string
          description: string
          total_amount: number
          billing_date: string
          journal_entry_id: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          event_id?: string | null
          unit_id: string
          description: string
          total_amount: number
          billing_date: string
          journal_entry_id?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string | null
          unit_id?: string
          description?: string
          total_amount?: number
          billing_date?: string
          journal_entry_id?: string | null
          created_by?: string | null
          created_at?: string
        }
      }
      billing_charges: {
        Row: {
          id: string
          billing_record_id: string
          scout_account_id: string
          amount: number
          is_paid: boolean
        }
        Insert: {
          id?: string
          billing_record_id: string
          scout_account_id: string
          amount: number
          is_paid?: boolean
        }
        Update: {
          id?: string
          billing_record_id?: string
          scout_account_id?: string
          amount?: number
          is_paid?: boolean
        }
      }
      payments: {
        Row: {
          id: string
          unit_id: string
          scout_account_id: string | null
          amount: number
          fee_amount: number
          net_amount: number
          payment_method: string | null
          square_payment_id: string | null
          square_receipt_url: string | null
          status: string
          journal_entry_id: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          unit_id: string
          scout_account_id?: string | null
          amount: number
          fee_amount?: number
          net_amount: number
          payment_method?: string | null
          square_payment_id?: string | null
          square_receipt_url?: string | null
          status?: string
          journal_entry_id?: string | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          unit_id?: string
          scout_account_id?: string | null
          amount?: number
          fee_amount?: number
          net_amount?: number
          payment_method?: string | null
          square_payment_id?: string | null
          square_receipt_url?: string | null
          status?: string
          journal_entry_id?: string | null
          notes?: string | null
          created_at?: string
        }
      }
      audit_log: {
        Row: {
          id: string
          unit_id: string | null
          table_name: string
          record_id: string
          action: string
          old_values: Json | null
          new_values: Json | null
          performed_by: string | null
          performed_at: string
        }
        Insert: {
          id?: string
          unit_id?: string | null
          table_name: string
          record_id: string
          action: string
          old_values?: Json | null
          new_values?: Json | null
          performed_by?: string | null
          performed_at?: string
        }
        Update: {
          id?: string
          unit_id?: string | null
          table_name?: string
          record_id?: string
          action?: string
          old_values?: Json | null
          new_values?: Json | null
          performed_by?: string | null
          performed_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}

// Convenience type helpers
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
